### ISSUE TITLE
Can this project run on Windows?

### ISSUE THREAD

**Issue by cp2296328845** [linkedtales/scrapedin-linkedin-crawler#10]
![image](https://user-images.githubusercontent.com/25115374/62418670-b38f1780-b6a1-11e9-99cd-f181f6dcb89f.png)
When I encountered this problem on windows10.

**Comment by leonardiwagner** [comment]
Hi @cp2296328845 this is a [puppeteer](https://github.com/GoogleChrome/puppeteer) error (a dependency of this project)

[There's a solution](https://github.com/GoogleChrome/puppeteer/issues/1425#issuecomment-359663629) which you can download chromium manually and point out the executable path, you can achieve that in this project editing the **[config.json](https://github.com/linkedtales/scrapedin-linkedin-crawler/blob/master/config.json)** file:

```
"puppeteerArgs": { "executablePath": "c://your//chromium//file.exe" }

```

**Comment by cp2296328845** [comment]
thank you very much



---Original---

**Comment by leonardiwagner** [comment]
Please let me know if it worked, thanks

**Comment by cp2296328845** [comment]
Maybe I have problems with the operation. It can not work.But on linux18 it can work.But i just get one message and then i can't use my account to log in.







------------------ 原始邮件 ------------------
发件人: "Wagner Leonardi"<notifications@github.com>;
发送时间: 2019年8月5日(星期一) 上午6:06
收件人: "linkedtales/scrapedin-linkedin-crawler"<scrapedin-linkedin-crawler@noreply.github.com>;
抄送: "梦里"<2296328845@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [linkedtales/scrapedin-linkedin-crawler] Can this project run onWindows? (#10)




Please let me know if it worked, thanks

**Comment by leonardiwagner** [comment]
Could you provide more info about how you can't use your account to log in?

**Comment by leonardiwagner** [comment]
closing due to lack of feedback
