### ISSUE TITLE
Save to excel

### ISSUE THREAD

**Issue by AIkr7** [linkedtales/scrapedin-linkedin-crawler#12]
Hey, can we save all result to excel? 
I am not a programmer so can you provide the code? please help me if you don't mind

Thanks

**Comment by leonardiwagner** [comment]
Here: https://github.com/linkedtales/scrapedin-linkedin-crawler/blob/master/README.md#tips

**Comment by AIkr7** [comment]
I am not a programmer, I don't know how to rewrite it. Maybe you can share the code here if you don't mind.

It would be helpful
