### ISSUE TITLE
Minor profile save issues

### ISSUE THREAD

**Issue by Netgator** [linkedtales/scrapedin-linkedin-crawler#14]
1.) If the config file attempts to save to a nested directory the mkDirSync is not creating the directory structure.
2.) The profile filenames are being saved as .json.json (not really an issue but looks odd.)

Pull request forthcoming...

**Comment by leonardiwagner** [comment]
alright, I just fixed the 2nd problem since it was quite simple and I had to update the version, the fix for 1st problem is welcoming, thank you.

**Comment by leonardiwagner** [comment]
oh, you already sent a PR , thank you I just merged :smile:
