### ISSUE TITLE
Crawl LinkedIn skills

### ISSUE THREAD

**Issue by tedvanderveen** [linkedtales/scrapedin-linkedin-crawler#16]
Hi! I'm looking for a way to extract a list of skills used by LinkedIn. This used to be not so hard until some two years ago, but not so anymore since the site structure changed. Any ideas on how to extract skill data?

**Comment by leonardiwagner** [comment]
@tedvanderveen Hi, are you talking about all linkedin or in a specific location? 

scrapedin only works for profile, and it's extracting the profiles skills, eg.:
```javascript
skills:
   [ { title: 'Data Analysis', count: '31' },
     { title: 'Research', count: '30' },
     { title: 'Psychology', count: '14' } ],
```

**Comment by tedvanderveen** [comment]
All LinkedIn skills. Full set. To be able to make sure to use same base set on our site versus what is being used at LinkedIn

**Comment by leonardiwagner** [comment]
@tedvanderveen The best shot about it is [looking in their official API](https://docs.microsoft.com/en-us/linkedin/) because that's about their private data. 

In this project, we're only able to collect public data, I'm sorry.
