### ISSUE TITLE
one bad profile scrap will throw error on whole process

### ISSUE THREAD

**Issue by tszjqgs** [linkedtales/scrapedin-linkedin-crawler#19]
not sure about other users, when the scraping come across one bad profile , the whole process will stop and throw error , would it be possible to just keep the error and keep move to the next profile scraping ?

**Comment by leonardiwagner** [comment]
Could you provide the error that appeared on the console?

We should be aware of what kind of error it is because sometimes it's better to fix the error to avoid losing information rather than just ignoring it.

Please check if you are using `scrapedin` version `1.0.10` on `package.json` and then run `npm install` to ensure that you are using the latest version of scrapedin

**Comment by tszjqgs** [comment]
2019-10-17T18:46:57.027Z error: error on crawling profile: https://www.linkedin.com/in/joann-ball-11662294 
 Error: linkedin: profile not found
(node:7266) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at crawl (/home/Downloads/scrapedin-linkedin-crawler/src/crawler.js:26:71)
    at <anonymous>
(node:7266) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7266) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

------------------------------------------------------------------
发件人：Wagner Leonardi <notifications@github.com>
发送时间：2019年10月18日(星期五) 03:47
收件人：linkedtales/scrapedin-linkedin-crawler <scrapedin-linkedin-crawler@noreply.github.com>
抄　送：tszjqgs <jason4ever8@aliyun.com>; Author <author@noreply.github.com>
主　题：Re: [linkedtales/scrapedin-linkedin-crawler] one bad profile scrap will throw error on whole process (#19)

Could you provide the error that appeared on the console?
We should be aware of what kind of error it is because sometimes it's better to fix the error to avoid losing information rather than just ignoring it.
Please check if you are using scrapedin``1.0.10 on package.json and then run npm install to ensure that you are using the latest version of scrapedin

**Comment by leonardiwagner** [comment]
Hi @tszjqgs you were right, in that case, we should skip, I fixed that: https://github.com/linkedtales/scrapedin-linkedin-crawler/pull/23/files

You can either do a `git pull` or apply those changes manually in your code
