### ISSUE TITLE
(node:11136) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!

### ISSUE THREAD

**Issue by stxts** [linkedtales/scrapedin-linkedin-crawler#2]
$ npm start

> scrapedin-crawler@0.0.1 start /Users/st/Desktop/panya/scrapedin-linkedin-crawler
> node src/index

(node:11136) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!
dlopen /Users/st/Desktop/panya/scrapedin-linkedin-crawler/node_modules/puppeteer/.local-chromium/mac-641577/chrome-mac/Chromium.app/Contents/MacOS/../Versions/75.0.3738.0/Chromium Framework.framework/Chromium Framework: dlopen(/Users/st/Desktop/panya/scrapedin-linkedin-crawler/node_modules/puppeteer/.local-chromium/mac-641577/chrome-mac/Chromium.app/Contents/MacOS/../Versions/75.0.3738.0/Chromium Framework.framework/Chromium Framework, 261): Library not loaded: /System/Library/Frameworks/MediaPlayer.framework/Versions/A/MediaPlayer
  Referenced from: /Users/st/Desktop/panya/scrapedin-linkedin-crawler/node_modules/puppeteer/.local-chromium/mac-641577/chrome-mac/Chromium.app/Contents/Versions/75.0.3738.0/Chromium Framework.framework/Versions/A/Chromium Framework
  Reason: image not found

TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/Users/st/Desktop/panya/scrapedin-linkedin-crawler/node_modules/puppeteer/lib/Launcher.js:342:14)
    at Interface.helper.addEventListener (/Users/st/Desktop/panya/scrapedin-linkedin-crawler/node_modules/puppeteer/lib/Launcher.js:331:50)
    at emitNone (events.js:111:20)
    at Interface.emit (events.js:208:7)
    at Interface.close (readline.js:368:8)
    at Socket.onend (readline.js:147:10)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
(node:11136) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11136) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by songthamtung** [comment]
work around is to downgrade puppeteer to 1.13.0

https://github.com/GoogleChrome/puppeteer/issues/4286#issuecomment-483385628

**Comment by leonardiwagner** [comment]
I set 1.13 as default version on scrapedin and [I updated this package](https://github.com/linkedtales/scrapedin-linkedin-crawler/commit/efb12b60cfcf14a8e3aef510ba58385ecea7fcac)

Thank you for your help :smile:
