### ISSUE TITLE
UnhandledPromiseRejectionWarning: ReferenceError: relatedProfiles is not defined

### ISSUE THREAD

**Issue by GiulioRossetti** [linkedtales/scrapedin-linkedin-crawler#28]
Hi,
I've setup the crawler but it stops after having crawled 2 profiles with the following error:

> (node:21269) UnhandledPromiseRejectionWarning: ReferenceError: relatedProfiles is not defined
    at crawl (/home/rossetti/PycharmProjects/LinkedinScraping/scrapedin-linkedin-crawler-master/src/crawler.js:31:55)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:21269) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

do you have insights on what can cause such an issue?

**Comment by leonardiwagner** [comment]
@GiulioRossetti fixed, please update your `crawler.js` code: https://github.com/linkedtales/scrapedin-linkedin-crawler/blob/master/src/crawler.js
