### ISSUE TITLE
Scrapper doesn't close browser

### ISSUE THREAD

**Issue by ghulammurtaza** [linkedtales/scrapedin-linkedin-crawler#29]
Scrapper doesn't close browser on exception or successful scrapping. If there are 100 profiles to scrap, it initiates 100 browser instances which creates memory issues.

**Comment by cyanide2019** [comment]
on ubuntu or centos ？did you  manage to scrape at least one profile yet?

**Comment by leonardiwagner** [comment]
that's true @ghulammurtaza , I just fixed that.

You can do a `git pull` from master, or update manually the fix with those changes: https://github.com/linkedtales/scrapedin-linkedin-crawler/pull/32/files

Please use `isHeadless: false` on config file, when it's `true` it can misbehave

**Comment by leonardiwagner** [comment]
closed due to lack of feedback
