### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by gmrperdigao** [linkedtales/scrapedin-linkedin-crawler#38]
Hi, i'm scrapping some URLs and in most of them (almost all) i'm receiving these warnings and error messages:

```
warn: [profile] profile selector was not found

warn: [scrollToPageBottom] page bottom not found

warn: [seeMoreButtons] couldn't click on button.pv-profile-section__see-more-inline, it's probably invisible

error: error on crawling profile: https://www.linkedin.com/in/IDENTIFIER/
 TypeError: Cannot read property 'replace' of undefined
```

I've already set `isHeadless` to `false` on `config.json` and updated the `scrapedin` version to the latest one (`1.0.14`)

**Comment by leonardiwagner** [comment]
@gmrperdigao please update the scrapedin version to v`1.0.16` it was fixed thanks
