### ISSUE TITLE
Irregular information loss when "maxConcurrentCrawlers" is greater than 1

### ISSUE THREAD

**Issue by sjwang222** [linkedtales/scrapedin-linkedin-crawler#4]
Hi there, this project is awesome and i have successfully used it to scrape some profiles. Thanks for sharing!
However, there is a small issue arising when i set 'maxConcurrentCrawlers' greater than 1. If so, some records on 'education' and 'position' are likely to be lost. Is this related to my internet speed or platform(OSX)? Thanks!

**Comment by leonardiwagner** [comment]
Hi @sjwang222 , first of all sorry for the late response.

And yes, it's due your internet speed.

You can also increase the profile waiting time [here](https://github.com/linkedtales/scrapedin-linkedin-crawler/blob/master/src/scrapProfile.js#L18) , changing from 5000 to a larger number such as 10000

**Comment by sjwang222** [comment]
@leonardiwagner Thanks for your reply~ That addresses my issues. By the way, i am curious about which part is to be adjusted when Linkedin.com updates its divs (like the changes in 12 June). Thanks!

**Comment by leonardiwagner** [comment]
@sjwang222 it's here: https://github.com/linkedtales/scrapedin/blob/master/src/profileScraperTemplate.js
