### ISSUE TITLE
 TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by gmrperdigao** [linkedtales/scrapedin-linkedin-crawler#42]
Hi, i'm scrapping some URLs and in some of them i'm receiving these warnings and error messages:

```
warn: [profile] profile selector was not found

warn: [scrollToPageBottom] page bottom not found

error: error on crawling profile: https://www.linkedin.com/in/IDENTIFIER/
 TypeError: Cannot read property 'replace' of undefined
```

I've already set `isHeadless` to `false` on `config.json` and updated the `scrapedin` version to the latest one (`1.0.16`)

Another question is if the program finishes after crawling all the profiles. I keep getting the message:
``` info: there is no profiles to crawl right now... ``` 
but it don't terminate the job

**Comment by leonardiwagner** [comment]
@gmrperdigao please update the scrapedin version to `v1.0.18` it was fixed

> Another question is if the program finishes after crawling all the profiles. I keep getting the message:
info: there is no profiles to crawl right now...
but it don't terminate the job

This is because it's quite hard to detect if there still profiles to scrape while scraping others, is that approach an issue to your business?
