### ISSUE TITLE
Crawler doesn't work

### ISSUE THREAD

**Issue by jeremy1392** [linkedtales/scrapedin-linkedin-crawler#7]
Hello,

Crawler doesn't work, it only scans the root profile.
(Even if we init a keyword list).

> 2019-06-27T13:01:12.099Z info: crawler finished: there are no more profiles found with specified keywords

**Comment by leonardiwagner** [comment]
Hi @jeremy1392 I fixed that bug at https://github.com/linkedtales/scrapedin-linkedin-crawler/commit/27e103c2b9481f7ebf3e577e287b6eb9bd96898d

Please clone again, or update your project with the above changes!

Please also report if it's working for you now, thank you!
