### ISSUE TITLE
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD Isseu

### ISSUE THREAD

**Issue by sumitrevin** [linkedtales/scrapedin-linkedin-crawler#8]
![image](https://user-images.githubusercontent.com/52994358/61355294-b2807c80-a891-11e9-8d0b-738d52935f94.png)

Getting this issue after clone your project and run sudo npm i command

**Comment by leonardiwagner** [comment]
Hi @sumitrevin , the error is basically what it says, lack of directory permission, you could solve that by giving permission to that directory:

 `sudo chmod -R 777 /var/www/html/scrapedin-linkedin-crawler/node_modules/puppeteer/`
