### ISSUE TITLE
Linkedin posts crawler

### ISSUE THREAD

**Issue by codewp** [linkedtales/scrapedin-linkedin-crawler#9]
Hi,

Thank you for this library.

It seems that it does not supports LinkedIn posts, so please let us know is it possible to crawl LinkedIn posts with this library or by adding custom codes to this library?

Thanks.

**Comment by leonardiwagner** [comment]
Sorry for the late response, I'm receiving a lot of personal requests both here and on my personal e-mail.

Since I do that only in my free time, for free, it's very hard to do private requests, but I'm gonna be willing to work on that if more people request the same, thank you.
